### ISSUE TITLE
Shuffling queues on *

### ISSUE THREAD

**Issue by MichaelXavier** [resque/resque#1075]
Appologies if there is another issue about this but I couldn't find one. I found it an odd choice that when \* is specified, workers process queues in alphabetical order. I can't imagine most apps name queues where the name is both sensical and in the order that they want the work processed. Seems to be 2 different concerns being conflated there.

What we've seen in production is that the default workers end up starving other queues if they hit a queue full of hard work that takes precedence alphabetically.

I took a look at WorkerQueueList and MultiQueue and it seems like the best solution would be to have WorkerQueueList to shuffle for the \* queue and for MultiQueue to use a circular list when popping jobs in the non-blocking interface. If not, I think that if the first queue in a list has a high volume of quick jobs and the second queue has a low volume of slow jobs, the slow jobs will get starved.

Thoughts?

**Comment by ermanc** [comment]
@steveklabnik I read the short discussion about this on http://librelist.com/browser//resque/2013/7/15/shuffling-queues-on/#4829b6fee392b1bca969781ba2462ac9

Though it doesn't seem like that went anywhere, there also doesn't seem to be any specific objections to this being at least a non-default option. 

We've been running into the issue of having one obnoxious queue blocking all other queues lexically below itself to be worked by our "general" workers (`QUEUE=*`).

Since the idea with `*` is that we don't necessarily care about the ordering (as you mentioned above) it might be possible to provide an environment variable flag to allow shuffling as part of glob pattern selection. 

This seems particularly simple, where all we might need is a simple `ENV['SHUFFLE']` check before `.sort`ing here: https://github.com/resque/resque/blob/master/lib/resque/worker.rb#L205, and do a `.shuffle` instead.

I will be getting a pull request ready, in case this sounds reasonable to you guys.
