### ISSUE TITLE
Launching workers with BACKGROUND=yes hangs with 1.25.0 

### ISSUE THREAD

**Issue by tjoneseng** [resque/resque#1122]
I upgraded from 1.24.1 to 1.25.0 and now my deploys hang when trying to start worker processes via rake with the BACKGROUND=yes flag.  I assume this is related to #895.  The command I'm using looks like this:

bundle exec rake BACKGROUND=yes INTERVAL=1 PIDFILE=/tmp/resque1.production.pid QUEUES=ts_delta RAILS_ENV=production environment resque:work

**Comment by rbroemeling** [comment]
@yaauie I agree that starting processes directly out of Capistrano isn't a great idea.  That said, discussion of that is beyond the scope of this ticket, which is fundamentally about resque's currently-broken daemonization behavior.

@codeodor Likely possible to test the redis connection before daemonizing, yes.  Again, I feel that is beyond the scope of this issue at present, however -- honestly, I'm not worried about fixing #967.  I consider the base report to be a little unrealistic ("I didn't get output when I was daemonizing a process" -- well of course you didn't, because by daemonizing it you explicitly said that you didn't want output).  If I _had_ to suggest a way forward to fix #967, though, testing redis connectivity before daemonization is a reasonable work-around to show the error; although I feel a stronger fix would be to refactor the logging in resque entirely such that it is more reasonable to log to flatfiles/logfiles (and thus making stdout/stderr output much less important overall).

**Comment by ches** [comment]
> If I had to suggest a way forward to fix #967, though, testing redis connectivity before daemonization is a reasonable work-around to show the error; although I feel a stronger fix would be to refactor the logging in resque entirely such that it is more reasonable to log to flatfiles/logfiles (and thus making stdout/stderr output much less important overall).

Or instead of refactoring logging if that's a pain (I haven't really looked closely at the current implementation for quite awhile), instead [rip out daemonization as a Resque "feature" entirely][1] and [guide people to use a proper service manager][2] :smile:

In all seriousness, that would avoid all sorts of issues/debates that are battles which every single long-running process implementation shouldn't have to fight. Might be worth considering for Resque's next major version bump.

[1]: http://www.mikeperham.com/2014/09/22/dont-daemonize-your-daemons/
[2]: http://www.mikeperham.com/2014/07/07/use-runit/

**Comment by steveklabnik** [comment]
I would be interested in making modernizations like that to Resque, though we'd have to just deprecate the older functionality, not remove it.
