### ISSUE TITLE
Is there a performance report about Resque?

### ISSUE THREAD

**Issue by noodles-v6** [resque/resque#1274]
In our project, there are a **looooooooot** of background jobs, such as **parsing web pages**, **downloading videos**, **determining web video's status**, etc. From our experiences, we evaluate that 50M jobs will need to consume. We are considering to use Resque as the background framework, so if a performance report will help us.

**Comment by yaauie** [comment]
That's really going to depend on the breakdown of your jobs (memory consumption, time spent in IO/wait, CPU time,job payload size, etc), the power of your worker machines (ram capacity & speed, CPU speed, network interface), and the power of your redis host.

With a very specific heterogenous breakdown of jobs, one of my 100-node worker clusters can churn through about 60M jobs in a day; any more and our (well-powered, 64GB RAM) redis host pegs its CPU, causing dropped redis connections & preventing workers from reporting completed or failed work.

An alternate that would be worth considering in your research is Sidekiq, which thankfully can be used almost interchangeably with Resque. My team found that it wasn't worth it for us to move to Sidekiq when we last explored the issue 2 years ago, but that was in part because of a memory leak in a third-party library we used that was mitigated by resque's process-per-job strategy, and not due to and specific fault with Sidekiq.

I'm closing this issue because it's not particularly actionable; in future, questions like this would be best directed at the mailing list, a link to which can be found in the project's readme.

**Comment by noodles-v6** [comment]
thank you!
