### ISSUE TITLE
Is it possible to run Resque with different version of Ruby than the Rails app requires?

### ISSUE THREAD

**Issue by patakijv** [resque/resque#1337]
We have a legacy Rails app that currently requires Ruby 1.8.7 (we use 1.8.7 REE in production) and Rails 2.3.14 and is using delayed_job as its background processor. We want to upgrade the background processing part to use Resque instead of delayed_job but noticed the current requirement is that minimum version of Ruby is 1.9.3. 

Is it possible for us to install 1.9.3 for Resque's purpose but when our application is run by Resque, it could still be using 1.8.7 as it does now? 

Or is there a way to allow Resque to run with 1.8.7? Even an older version?

Thoughts?

The reason we want to do this is because it is a much larger effort (and would required a bigger approval process) to start upgrading the rest of the application to use a new Ruby version.

**Comment by pglombardo** [comment]
Since the activity on this project is a bit low lately, I'll throw in my 2 cents.  This could be possible depending on two things:

1. if your jobs and their dependencies can independently run under a newer ruby version.
2. If Resque enqueue works under 1.8.7 (you likely still need to queue from your core application)

You would have to create a new Ruby 1.9.3+ project that loads only resque, your jobs and their dependencies.  You could then run your resque workers from this new project.

Then the critical test is to see if the client side `enqueue` works without issue from your existing Ruby 1.8.7 app.

So the bottom line is that it really depends on what your jobs are doing and if they are compatible with the newer ruby version and if you can get `enqueue` to work with your existing app.

**Comment by steveklabnik** [comment]
Thanks @pglombardo ! That's accurate. Also, since Resque 2 is gone, Resque 1 still supports 1.8.7.
