### ISSUE TITLE
what's the diffrence start and not start workers?

### ISSUE THREAD

**Issue by luoguanzhong** [resque/resque#1341]
My `resque` version is 1.25.2.

When I doesn't start a worker after my rails app started, it seems `resque` works well when I use the code below:

```ruby
Resque.enqueue(ChechparamsInstance)
```
So, what's the different  start and not start workers? @defunkt

**Comment by yaauie** [comment]
Resque is a delayed work engine; enqueueing work puts it on a redis-backed queue to be done later, allowing your code to proceed without blocking on work that *can* be done later; this is helpful when serving up requests that are time-sensitive. For example, if your web app needs to send an e-mail as part of a user's request, usually the person waiting on the other end of the line would rather receive a lightning-fast response indicating that their request was being processed, instead of the page taking a long time to load while your web app went through the motions of composing their message and comminicating with SMTP servers to send the e-mail.

But *putting* work on a queue is not enough; your app needs to have one or more worker processes *picking up* work from your queues, or else the delayed work never actually gets done.

Resque *can* be run in inline mode, circumventing the queue and workers to run the job in a blocking fashion in order to simplify local development; if your work is getting done without having workers running, it is because your code contains `Resque.inline = true`.

**Comment by luoguanzhong** [comment]
@yaauie thanks, so the `Resque.inline` is default true.

**Comment by yaauie** [comment]
@luoguanzhong no; `Resque.inline` defaults to `false`.

**Comment by luoguanzhong** [comment]
@yaauie thanks again, I got it.
