### ISSUE TITLE
undefined method `formatter=' error in 1.26.0

### ISSUE THREAD

**Issue by tjoneseng** [resque/resque#1433]
Thrown at resque-1.26.0/lib/resque/worker.rb:849 for Rails 3.2.22.2.

**Comment by chrisccerami** [comment]
Would it be possible for you to provide some more of the error detail and a stacktrace? `Resque.logger` by default should be defined as `MonoLogger.new(STDOUT)`, and it's formatter by default is the `Resque::QuietFormatter`, so it would be helpful to know what the undefined method is trying to be called on. If the error is `undefined method formatter= for nil`, then we know we have a problem where no logger is set, for example, whereas if it said `undefined method formatter= for #<MonoLogger:0x007fd0512d81c8>` then there's a whole separate issue.

**Comment by gmcnaughton** [comment]
I think this happens if you try to set `Resque.logger` to an instance of `ActiveSupport::BufferedLogger` under Rails 3.2.x (or a `Log4r::Logger`).  For instance:

```ruby
Resque.logger = ActiveSupport::BufferedLogger.new(Rails.root.join('log', 'resque.log'))
```

Trying to run workers results in this error:
```
$ QUEUE=* rake resque:work
rake aborted!
NoMethodError: undefined method `formatter=' for #<ActiveSupport::BufferedLogger:0x007fc5047e6000>
gems/ruby-2.2.3/gems/activesupport-3.2.22.2/lib/active_support/tagged_logging.rb:72:in `method_missing'
gems/ruby-2.2.3/gems/resque-1.26.0/lib/resque/worker.rb:849:in `verbose='
gems/ruby-2.2.3@kartofflly/gems/resque-1.26.0/lib/resque/worker.rb:130:in `initialize'
gems/ruby-2.2.3@kartofflly/gems/resque-1.26.0/lib/resque/tasks.rb:13:in `new'
...
```
In Rails 3.2.x, `BufferedLogger` did not subclass of `Logger`, and did not quack to the `#formatter=` method.  As of Rails 4, `BufferedLogger` subclasses `Logger` and the problem should be fixed.

If you're using Log4r, I'm not sure there's a workaround yet (see https://github.com/colbygk/log4r/issues/43)

**Comment by jeremy** [comment]
All things considered, I think we're well off expecting this duck type from the logger. Those using exotic Loggers may provide a wrapper class or mixin that conforms with the stdlib logger API.
