### ISSUE TITLE
1-x-stable / master

### ISSUE THREAD

**Issue by Sirupsen** [resque/resque#1473]
@steveklabnik @chrisccerami @davetron5000 do any of you know what the deal is with these two branches? I merged two PRs to master, and ended up cherry-picking them to 1-x-stable. Is 1-x-stable only for released tags? Can we get rid of 1-x-stable now that master is no longer Resque 2?

**Comment by Sirupsen** [comment]
cc @dylanahsmith @fw42

**Comment by steveklabnik** [comment]
`1-x-stable` should be vestigial at this point. I didn't delete it because there were some open PRs I didn't want to force contributors to move over.

**Comment by steveklabnik** [comment]
(so yes, you should be able to just get rid of it onw)

**Comment by Sirupsen** [comment]
Thanks @steveklabnik. I'll delete the branch and  👀  at current PRs against the now defunct branch.

Great work cleaning up all those old PRs ✨

**Comment by Sirupsen** [comment]
Argh, there's a larger difference between the two branches than I expected :/ I have to run, but maybe @dylanahsmith can take a look at this (since you're looking at Resque right now).

**Comment by steveklabnik** [comment]
At the time I left it, there wasn't :sob:

**Comment by dylanahsmith** [comment]
There are 6 merges into 1-x-stable since v1.26.0.

* #1440 merged 1-x-stable to bring in #1439 and #1425
* **#1403 was merged into 1-x-stable and is missing in master**
* #1210 cherry-picked #1466 from 1-x-stable as commit 4bb44413a045fca78d25e22ad535b3f5ea97fab8 without a reference to the PR number
* #1472 and #1471 got cherry-picked from master as squashed merge commits

@chrisccerami you merged #1403 into 1-x-stable, would you mind bringing that into master.  Please keep a reference to the original PR number in the commit you bring over

**Comment by fw42** [comment]
Any objections to deleting the 1-x-stable branch now?

**Comment by dylanahsmith** [comment]
No objections from me
