### ISSUE TITLE
worker does not start - no error message

### ISSUE THREAD

**Issue by AntonTrapp** [resque/resque#1508]
```
rake resque:work QUEUE=* --trace

** Invoke resque:work (first_time)
** Invoke resque:preload (first_time)
** Invoke resque:setup (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute resque:setup
** Execute resque:preload
** Invoke resque:setup
** Execute resque:work
```

Prompt. No worker anywhere to be found.

Nothing else happening. The redis FLUSHALL hint from #1013 does not help.

> resque version is at 1.25.2
> redis version is stable 3.2.3 (bottled), HEAD (homebrew)
> system: Mac OS X 10.11.6

**Comment by toppy42** [comment]
I am also having this problem

**Comment by chrisccerami** [comment]
@toppy42 what version of Resque are you using?

**Comment by toppy42** [comment]
Thanks for the quick response!  Nevermind, it was user error.

I've never set up resque from scratch before so I didn't realize you needed `Resque.logger.formatter = Resque::VerboseFormatter.new` and `Resque.logger.level` to be set before debug output would be seen.  I thought resque was hanging when in fact it was waiting for work.

The reason I didn't think work was being done is because my job was inheriting from `ActiveJob::Base` which was somehow superseding my perform definition (but not actually doing anything).  Still confused by this.

I think it's safe to close this issue, but it might be helpful to have a command line option to show debug output.  I expected `--trace` to do that.

Sorry for the confusion, Thanks!
