### ISSUE TITLE
Why no timestamp in VERBOSE mode?

### ISSUE THREAD

**Issue by ysyyork** [resque/resque#1517]
I don't want the extra logging that VVERBOSE mode provide. But I do want timestamp. I saw a pull request long time ago (https://github.com/resque/resque/pull/323) that added timestamp to VERBOSE mode, but why now it's rolling back? Missing timestamp makes it really hard to find system bugs if I cannot figure out when it happens.

**Comment by chrisccerami** [comment]
As was commented in the pull request you linked, the only difference I can see between verbose logging and very verbose logging is the addition of the timestamp and the PID. It seems reasonable to me that you could simply use very verbose logging if you want timestamps, rather than Resque making those two logging levels almost identical.
