### ISSUE TITLE
Errno::EIO: Input/output error during worker.rb:linux_worker_pids

### ISSUE THREAD

**Issue by nisaraf** [resque/resque#1522]
I noticed an EIO error coming up with the following stacktrace every once in a while (not always). What could be going wrong?

/gems/activesupport-4.0.13/lib/active_support/core_ext/kernel/agnostics.rb:7 in `
/gems/activesupport-4.0.13/lib/active_support/core_ext/kernel/agnostics.rb:7 in `
/gems/resque-1.24.1/lib/resque/worker.rb:596 in linux_worker_pids
/gems/resque-1.24.1/lib/resque/worker.rb:582 in worker_pids
/gems/resque-1.24.1/lib/resque/worker.rb:426 in prune_dead_workers
/gems/railties-4.0.13/lib/rails/commands/runner.rb:53 in <top (required)>
/gems/railties-4.0.13/lib/rails/commands/runner.rb:53 in eval
/gems/railties-4.0.13/lib/rails/commands/runner.rb:53 in <top (required)>
/gems/railties-4.0.13/lib/rails/commands.rb:84 in require
/gems/railties-4.0.13/lib/rails/commands.rb:84 in <top (required)>
bin/rails:4 in require
bin/rails:4 in <main>

**Comment by chrisccerami** [comment]
The stacktrace would indicate that the error is happening when trying to shell out to find the PIDs of all the workers in order to prune dead ones. The EIO would imply that the worker has lost its connection STDIN/STDOUT, which I could imagine would cause problems when using a command like `ps` which attempts to print to STDOUT. Can you provide any more information about your environment or about the issue?
