### ISSUE TITLE
CSV object converted to 2D array

### ISSUE THREAD

**Issue by arpansac** [resque/resque#1548]
Whenever I am sending CSV object (from an uploaded file using CSV.read()) to a worker via resque, it converts the object to a 2D array.

However, if the same worker is called directly on the server, it works absolutely fine.

**Comment by chrisccerami** [comment]
Do you mean that you are trying to pass a CSV object to a Resque worker through Redis?

**Comment by arpansac** [comment]
Probably yes, It'd be great if you could help me out! Probably I'd need some more insights.

**Comment by chrisccerami** [comment]
Complex objects aren't capable of being passed into Redis, so I would assume that when trying to marshal a CSV object it converts it to a 2D array and then writes that to Redis. In general it's easier to pass only simple data to Resque because of this. So for example, if you need to find a series of database records and a build a CSV out of them, then you can instead pass their IDs to Resque and let it query for them. If you have a User uploading a CSV and you want to pass that to Resque, it would probably be easier to save that file somewhere and then pass an identifier to Resque for it to retrieve the file.

**Comment by arpansac** [comment]
Thanks a lot for the clarity. It's good that the object is converted to 2D array at least!

Actually I'm uploading a csv and creating a database from it. Don't want to save the file, just want to read the contents from the params directly.

**Comment by chrisccerami** [comment]
🖒 glad I could help
