### ISSUE TITLE
Number of connections per worker (master)

### ISSUE THREAD

**Issue by boricic** [resque/resque#1570]
Hey guys,

I'm experiencing a strange issue. I have 80 something Resque workers crunching some data and `maxclients` set to 128 on RedisToGo.

Every now and then I get `ERR max number of clients reached`. Now I'm wondering whether one worker (master) keeps exactly one connection to Redis or can it be more?

**Comment by zreisman** [comment]
Is this the Redis instance that Resque is using?  Are you using it for anything else? If so, are you creating a sep. connection or using `Resque.redis` directly?  Each worker has a master process that forks for each job it pulls off the queue, so that may actually be up to 160 connections. You may need to look into configuring the inherit_socket property for the Redis connection.

**Comment by boricic** [comment]
That is a Redis instance dedicated to the Resque. After looking a bit through the code I realized that you're right. Theoretically it could be 160 connections. I'll just try and configure max number of connections in RedisToGo.

Thanks!
