### ISSUE TITLE
Resque + Mongoid

### ISSUE THREAD

**Issue by dimasusername** [resque/resque#1585]
There is a section in Readme in regards to MySQL and ActiveRecord. However, what about Mongoid?

In our set up we frequently get stuck workers that just do nothing for hours. Can it be related to how we connect to Mongoid? I read a bunch of info about limiting number of connections when forking and how it's irrelevant with Mongoid >4 because it uses connection pooling. I also moved `Mongoid.load!` to `'resque:setup'` task inside the Rakefile.

If anyone can share any insight I'd be very grateful.

**Comment by chrisccerami** [comment]
Hey @dimasusername, unfortunately I don't know anything about Mongoid, but hopefully someone will see this who had some insight for you. If and when you resolve your issue, please feel free to submit a documentation PR to explain what you learn.

**Comment by subashkc** [comment]
Is there any updates on this? I was looking for articles or documentations on how to do this and if someone has some suggestions, they'd be much apprerciated

**Comment by dimasusername** [comment]
I created this issue on Mongoid Jira Board https://jira.mongodb.org/browse/MONGOID-4527

As I understand it, a connection to MongoDB is made for EACH job processed by the worker. In our environment, we process millions of jobs every day so making a new connection to the MongoDB server every time is very inefficient. Is there anything I can do to make Resque use a pool of connections?

**Comment by jeremy** [comment]
Connection pooling is a possibility if your MongoDB client can safely pass the socket from the parent process to the forked child. Most libraries see this as user error (as it commonly is) and prohibit or prevent it, but with some digging you may be able to get something working.

Alternatively, use one of the multi-jobs plugins (resulting in 1 conn per N jobs rather than 1 per job), or perhaps use a pooling proxy like http://blog.parseplatform.org/learn/engineering/dvara/
