### ISSUE TITLE
MySQL aborted connections

### ISSUE THREAD

**Issue by CR4567** [resque/resque#1598]
Hi,

in my MySQL / MariaDB Logs I see lots of Warnings:
`[Warning] Aborted connection 210 to db: '***' user: '***' host: 'localhost' (Got an error reading communication packets)`

These warnings occur always when a resque job queries the database...
From the documentation, it explains, that a connection is established but not closed correctly.
In the DB logs I also see the query and that there is no "COMMIT" or "QUIT" at the end.
For any other rails query there is a finishing command.

So the jobs is working correctly but it doesn't seem to close it afterwards.

Is that a normal behavior of resque or did I configure something wrong?

**Comment by jeremy** [comment]
Unrelated to Resque. Check out https://github.com/brianmario/mysql2/issues/606 for more.

**Comment by jweir** [comment]
Hi @jeremy but, perhaps it is related to Resque because of how the process exits.

`Kernel.fork { ApplicationRecord.connection; exit! }`

Will produce an `Aborted connection` warning in MySQL 5.7, Rails 5.2.2, mysql gem 0.5.2.

After the perform is run, Resque calls `exit!` which immediately ends the program – no chance to close a connection.

https://github.com/resque/resque/blob/1d85f7c705ee8a609531c29035f8cf7cc6d67b19/lib/resque/worker.rb#L898

So, why `exit!` vs `exit` or nothing?

**Comment by jeremy** [comment]
Good point @jweir. Note the conditional there. When `exit!` is called, the `ensure` clause is not invoked by Ruby. See the change from `exit!` → `exit` and later revert here: https://github.com/resque/resque/pull/307#issuecomment-1271733

We could refactor to not rely on that behavior.

**Comment by jweir** [comment]
Thank you for tracking down the change!  I started a new issue about this at https://github.com/resque/resque/issues/1664
