### ISSUE TITLE
Restart job on worker restart

### ISSUE THREAD

**Issue by Paxa** [resque/resque#1686]
Now if I have long-running job and I restart worker then that job become failed
Usually it happens when I deploy and I need to restart those jobs manually.
```
Exception
Resque::PruneDeadWorkerDirtyExit
Error
Worker worker-6877dbc77f-gbpwq:1:* did not gracefully exit while processing ActiveJob::QueueAdapters::ResqueAdapter::JobWrapper
```

Is it possible to make it re-add job to queue when process exists?

**Comment by jeremy** [comment]
You can use QUIT to wait for jobs to finish before restart, instead of TERM for immediate restart: https://github.com/resque/resque#signals

If you need to TERM anyway, you can investigate a retry plugin, like https://github.com/lantins/resque-retry, that uses a failure backend to reenqueue failed jobs.
