### ISSUE TITLE
Old workers expiration issue

### ISSUE THREAD

**Issue by hackhowtofaq** [resque/resque#1704]
https://github.com/resque/resque/blob/adb633a0f6b98b1eb5a5a85bb36ebac9309978fd/lib/resque/worker.rb#L486

Since `worker.to_s` includes the pid, older workers with different pid but seconds_since_heartbeat > prune_interval are not expired.

Are you aware of this? Is this intended?

**Comment by josh-m-sharpe** [comment]
I frequently notice after a deploy when old workers are killed and new ones started, the worker count in resque web is elevated inaccurately.  Do you think this is related?

**Comment by hackhowtofaq** [comment]
I've also noticed this. Yeap I think it has to do with the above issue.

**Comment by josh-m-sharpe** [comment]
Seems like there's additional information here:

https://github.com/resque/resque/blob/adb633a0f6b98b1eb5a5a85bb36ebac9309978fd/lib/resque/worker.rb#L605-L610

**Comment by iloveitaly** [comment]
I've run into this as well. I wonder if we could add a configuration option to prune these workers automatically. If a user knows they aren't using an old version of resque or other client library, they could set the configuration option to auto-prune these workers.

If someone could whip up a PR I can help review and get it merged!

**Comment by jrochkind** [comment]
In my experience simply running `Resque::Worker.all_workers_with_expired_heartbeats.each(&:unregister_worker)` does succesfully prune these. 

It's the more complicated logic in [#prune_dead_workers](https://github.com/resque/resque/blob/adb633a0f6b98b1eb5a5a85bb36ebac9309978fd/lib/resque/worker.rb#L594) that is maybe deciding they are not actually prune-able, perhaps because of what @hackhowtofaq explains. 

It's just unclear to me what this more complicated logic is intended to do. Cause certainly one PR that would fix this problem would be just replacing #prune_dead_workers with the simple implementation `Resque::Worker.all_workers_with_expired_heartbeats.each(&:unregister_worker)` -- but what would that be *losing*, what is the more complicated logic meant to do?  

If there aren't docs or tests about this, this is what makes it challenging to work on an under-maintained "legacy" project like this, there's nobody around with the context to understand what's up, so someone kind of has to spend some time trying to re-construct it archeologically to make changes safely. 

Or we could just replace the implementation with ``Resque::Worker.all_workers_with_expired_heartbeats.each(&:unregister_worker)`  and if no tests fail say that's good enough? Seems risky.

**Comment by iloveitaly** [comment]
Pretty sure this is related to https://github.com/resque/resque/issues/1750 which has a PR associated with it. Hoping we can get that PR merged soon.

**Comment by iloveitaly** [comment]
#1750 has been merged and should fix this issue! Re-open this issue if it's still a problem.
