### ISSUE TITLE
New fork https://github.com/hackhowtofaq/resquex

### ISSUE THREAD

**Issue by hackhowtofaq** [resque/resque#1705]
I am planning to start working on my fork to address my pain points.

If your pain points are the same, please do not hesitate to comment on my issues.

https://github.com/hackhowtofaq/resquex

**Comment by junaruga** [comment]
Thank you for your action.
Do you like becomng a maintainer of this repository adding you to the resque organization?

**Comment by hackhowtofaq** [comment]
Yeap no problem. I will do my best.

**Comment by jeremy** [comment]
Forking and filing pull requests is the way to address pain points. Active maintenance participation is welcome, too. That starts with addressing open issues and filing pull requests. ❤️

**Comment by hackhowtofaq** [comment]
@jeremy if you want pull requests you should be more active here. There are open issues with no comments from the team. It took 18 days to answer this https://github.com/resque/resque/issues/1702

**Comment by rafaelfranca** [comment]
There is no new PR since December 2019 and except for the jquery upgrade (which has failing tests) nothing is pressing that we need to merge and review. So you can start by sending the PRs and addressing the open issues if what you want is activity. If you plan to maintain a fork or this repository you will have to do that anyway.
