### ISSUE TITLE
Question/Bug?: Why is pagination reversed?

### ISSUE THREAD

**Issue by josh-m-sharpe** [resque/resque#1712]
Why is pagination reversed and zero-based on the Queue page:

<img width="108" alt="Screen Shot 2020-04-05 at 2 43 07 PM" src="https://user-images.githubusercontent.com/39473/78507041-d0f21500-774b-11ea-8a71-5f4dee6bbeee.png">

instead of 'normal' ?

<img width="145" alt="Screen Shot 2020-04-05 at 2 42 57 PM" src="https://user-images.githubusercontent.com/39473/78507050-dfd8c780-774b-11ea-9b1d-295362a0a003.png">

**Comment by lex3001** [comment]
+1 for this needing to be fixed.
When I view Failed in the UI, it sometimes defaults to Page 0, which are not the most recent failures. Then I have to click on Page 1 manually to see the most recent ... but wouldn't 0 have the most recent, not 1, since they are ordered by most recent at the top?

**Comment by jeremy** [comment]
https://github.com/resque/resque/pull/917

**Comment by lex3001** [comment]
Hi @jeremy thanks for the link to 917. I am still at a loss though as to how to fix this. For example, I have two pages of failures. I open Failures and it shows Page 0 (Page 1 would be most recent) with the most recent failure from Page 0 at the top. It should open on the page with the most recent failures (Page 1 in my example) with the most recent at the top. Are you saying this can't / won't be fixed due to something written in 917 ("its complicated" to paraphrase) or that it is by design or something else? Thank you!
