### ISSUE TITLE
Is there a way to customize the Sinatra frontend? 

### ISSUE THREAD

**Issue by matthewhively** [resque/resque#1728]
I would like to change some aspects of the layout for web server frontend. I'm assuming I can create a copy of the erb template files in my rails app somewhere, and have them loaded instead of the built in gem versions.
Where would the override view files be placed in the rails directory structure?

Or is there some other system for customization?

**Comment by shaul75** [comment]
Fork it

**Comment by jeremy** [comment]
The bundled resque-web is a Sinatra app, so you can monkey-patch it. Check out how resque-schedule adds new tabs and new routes to the base UI: https://github.com/resque/resque-scheduler/blob/master/lib/resque/scheduler/server.rb

Overriding existing views is a trickier matter. Dig around in the code to deduce where & how to override.

Alternatively, try out the newer [resque-web](https://github.com/resque/resque-web) Rails app. Since that's a Rails app, you can do things like prepend your own view paths.
