### ISSUE TITLE
Plan for a new release?

### ISSUE THREAD

**Issue by amangup** [resque/resque#1738]
Hi,

I see that the latest release for resque was over 2 years ago. There are some features in code (like worker_exit hook), that is not available in the 2.0.0 build. Is there a plan to go for another release?

Thanks,
Aman

**Comment by iloveitaly** [comment]
@amangup this is a great idea. Would you mind submitting a PR with:

* A version update to the gemspec (maybe 2.0.1?)
* Updated history.md. Looking at the [changes since the 2.0.0 commit](https://github.com/resque/resque/compare/158c7ccd5871db0f7ff9d94d6dabfd2a74b6e02a...master) there are a bunch of missing entries

We should be able to get a new release cut with that work done!

**Comment by jrochkind** [comment]
I will see if I can find some time this week to do this. If there are new features (you mention "worker_exit"), that probably means it should be 2.1.0 rather than 2.0.1 -- not sure if resque explicitly adopts semantic versioning, but either way it is a good guide even if not committing to it absolutely, and says new versions should be minor version bump, patch-level reserved for bugfix-only releases, which makes sense to me.

**Comment by iloveitaly** [comment]
@jrochkind I'm not sure how strictly semver was held to in the past, but we should definitely adopt it going forward. Thanks for offering to help here!

**Comment by iloveitaly** [comment]
New release is out! https://rubygems.org/gems/resque
