### ISSUE TITLE
Figure out Resque Unique jobs

### ISSUE THREAD

**Issue by ruckus** [resque/resque#1841]
On Nov 3 2022 Luis and I thought we discovered that the `include Resque::Plugins::UniqueJob` plugin wasnt working.

The morning of Nov 4 I took another stab at attempting to prove it wasnt working

```ruby
class DummyJob < BaseJob

  include Resque::Plugins::UniqueJob

  @queue = :default
  attribute :raise_exception
  attribute :name
  attribute :color

  def self.redis_key(payload)
    "dog1"
  end

  def initialize(name = "none", color = "green")
    @name = name
    @color = color
  end

  def self.perform(arguments = {})
    process(arguments) do
      logger("sup!!")
      message = "Hi, #{arguments['name']} my name is #{self.to_s}"
      puts message
      sleep 10
      logger(message)
      #raise "Couldnt do something"
      #SupportMailer.dummy("toolbag@gmail.com", "hello world").deliver_now
    end
  end

end

```

And then calling this job 4 times

```ruby
4.times { DummyJob.new("taco", "dog").spool! }
```

and it appears to be working :( or :) ?

need to dig deeper

**Comment by pboling** [comment]
@ruckus I maintain (debatable, as I am not currently using resque, but I had been somewhat recently) a suite of resque extension gems.  I was using them to successfully run a complex cornucopia of intricately configured jobs at a rate of several billions per month.

I rewrote, and renamed, both `resque_solo` and `resque-lonely_job`, because they
 can't be used together, but since one offers run time uniqueness, and the other queue time uniqueness, I needed both.  Why?  Their `redis_key` methods directly conflict, among other more subtle conflicts.

Re:`resque-lonely_job` - it hasn't been maintained since 2014.  @wallace, its author, transferred control to me, and I plan to create a migration path from [`resque-lonely_job`](https://github.com/wallace/resque-lonely_job) to [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime) - it was a very _careful_ rewrite looking ahead to minimally painful upgrades...

The following allow complete control over handling of uniqueness for jobs (a la carte):

- [`resque-unique_by_arity`](https://github.com/pboling/resque-unique_by_arity) - Allows fine-tuned handling of arity (argument composition) comparisons for determination of job uniqueness
- [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime) - Job run time uniqueness 
- [`resque-unique_in_queue`](https://github.com/pboling/resque-unique_in_queue) - Job queue time uniqueness

NOTE: I am in the process of officially moving all three to this Resque organization.

You may have better luck with them!

**Comment by ruckus** [comment]
Thanks @pboling for the update. I now realize I thought I had opened an Issue on my own repo and not here in public 🤣 .

I will check out your other gems. Thanks again.

**Comment by pboling** [comment]
They are now all on the Resque org!
