### ISSUE TITLE
prune_dead_workers doesn't work on heroku cedar

### ISSUE THREAD

**Issue by dhiemstra** [resque/resque#319]
Because heroku run's every process in a separated closed environment the `ps` command doesn't list any worker processes.

We are currently running in some problems with heroku because they don't gracefully kill workers on deploy or restart.
This causes old workers to stay "alive" in redis. I'm not really sure if either heroku should kill workers gracefully or if resque should look into an other way to check alive workers.
It might be an idea to let a worker update a timestamp or something in redis once in a while and that resque will cleanup workers which havn't checked in for x seconds/minutes. I would be open to contribute for this issue but would like to discuss things first (maybe there is already a solution or i just do something wrong).

**Comment by aaani** [comment]
Not sure why this issue was closed. I see two issues in Rails (4.2.4)  and resque (1.25.2)
  - I see a lot of phantom/dead workers in the web interface. 
  - Heroku Cycling restart causes the following error: 2015-11-19T21:47:48.887585+00:00 heroku[resque.1]: Error R12 (Exit timeout) -> At least one process failed to exit within 10 seconds of SIGTERM

**Comment by steveklabnik** [comment]
@aaani as I said two and a half years ago:

> Without a good reproduction, I'm not going to be able to help fix this.
