### ISSUE TITLE
Consider using oj gem for JSON load/dump

### ISSUE THREAD

**Issue by jonhyman** [resque/resque#903]
From #902:

> We use [Oj](http://www.ohler.com/dev/need_for_speed/need_for_speed.html) in our API ([docs](http://www.ohler.com/oj/)); Oj is the fastest JSON library out there for Ruby. When we switched our API to use it instead of the default, we saw a noticeable speed increase in API response times, as our profiler indicated that much time was spent in JSON encoding.

master uses the JSON gem, which is slower than Oj.

**Comment by Jacobkg** [comment]
@steveklabnik We are back on MultiJson for 1-x so is there anything left to do for this issue?

**Comment by steveklabnik** [comment]
Maybe not. I would like to get re-antiquated with the problem, since I'm a little out of the gem loop these days. I thought `MultiJson` wasn't really needed anymore directly, but that knowledge might be out of date. Basically, my feel is still https://github.com/resque/resque/issues/903#issuecomment-16145099

In other words, I see this ticket as "investigate keeping functionality while removing multijson if possible" rather than "add multijson to a no-longer existing branch"

**Comment by yaauie** [comment]
@steveklabnik a while ago I remember you abstracting out the encoder; would this be a suitable place to allow someone to provide a plugin that provides its own encoder that is backed by oj/protomodel/yanl/whatever?

**Comment by steveklabnik** [comment]
Yes, possibly. The details are a bit too paged-out of my brain right this moment, so here's the high level:

1. I would like to allow people to use their own encoders.
2. I'm not sure MultiJson is the right way to do that anymore.
3. I don't know what the exact right way is.
