### ISSUE TITLE
Can not Resque.new

### ISSUE THREAD

**Issue by ponny** [resque/resque#976]
I'm having a huge amount of trouble getting Resque to work.  I must be missing something very big because I'm following the steps from your README.  I'm using Rails 4:

2.0.0dev > Resque::VERSION
 => "1.24.1" 
2.0.0dev > Resque.new
NoMethodError: undefined method `new' for Resque:Module

Same issue with master:
gem 'resque', :git => 'git://github.com/resque/resque.git'

This would not work:
gem "resque", "~> 2.0.0.pre.1" 
Because: 
Could not find gem 'resque (~> 2.0.0.pre.1) ruby' in the gems available on this machine.

**Comment by cdrage** [comment]
As per https://github.com/resque/resque/commit/4b04fb8cfafe1e22976954aea5df6f1b701ee161

and http://words.steveklabnik.com/rescuing-resque-again

_"We will plan on making this switch in the next couple of weeks. If you feel this is the wrong move, please let us know. But since active development will in fact happen on 1.x, this feels like the correct thing."_

Let's close these issues? #1175

**Comment by steveklabnik** [comment]
Yes, this is a good point, thanks!
